### ISSUE TITLE
DeviceManager.DeviceByID can't find device until enumerate is called

### ISSUE THREAD

**Issue by dylanhitt** [frida/frida-go#27]
Looking through the core source I realize this is expected. 

The other bindings (at least what I looked at) do not provide a method similar to this, most involve instantiating DeviceManager in a function and or finding a shared one and then simply returning a device. Similar to the `frida.GetDeviceById` in this module.

So in this case DeviceManager.DeviceByID should either enumerate the devices or at the very at least in the doc string express that before calling DeviceByID that the deviceManager must first enumerate the devices.

I'd be happy to provide a PR for either direction.

Cheers!

**Comment by NSEcho** [comment]
Hey, I want to keep the `Frida.GetDeviceById` so that the user has the options to either follow the usual route(get device manager, enumerate devices and select the device) or they can grab it right away (doing the work in the background). 

Based on all of this, I would much rather keep it the way it is right now, and you are right, doc string should be updated to let the user know.
